function [Z0_periodic, jacobian] = PM_periodic_sol(Z0)
    opts = optimoptions('fsolve', ...
        'Display',        'iter', ...     
        'Algorithm',      'trust-region-dogleg', ...
        'FunctionTolerance', 1e-10, ...
        'StepTolerance',     1e-10, ...
        'MaxIterations',     1000, ...
        'MaxFunctionEvaluations', 5000);
    [Z0_periodic, ~, ~, ~, jacobian] = fsolve(@(Z)(Poincare_map(Z) - Z), Z0, opts);
end